"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_component/Header/Header";
import Footer from "./_component/Footer/Footer";
import Shope from "./_component/Shope/Shope";
import { Toaster } from "react-hot-toast";
import { usePathname } from "next/navigation";
import { Provider } from 'react-redux';
import store from "./Redux/Store/Store";
import Up from "./_component/up/Up";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });


export default function RootLayout({ children }) {
  const path = usePathname();
  const showHeader = path == "/Signin" || path == "/Signup" ? false : true;

  return (
    <html lang="en" className="scroll-smooth">
            <Head>
        <title>E Commerce</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Provider store={store}>
      <body className={inter.className}>

<Toaster />
<Shope />
{showHeader && <Header />}
<Up />
{children}
<Footer />
</body>
      </Provider>
 

    </html>
  );
}
